proyec_inmobiliariaPilar/pilar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('apps.inicio.urls'))),
    path('clientes/', include(('apps.persona.urls'))),
    path('propiedad/', include(('apps.propiedad.urls'))),
    path('busqueda/', include(('apps.busqueda.urls'))),
    path('contrato/', include(('apps.contrato.urls'))),
    path('contacto/', include(('apps.contacto.urls'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estadisticas/', include(('apps.estadisticas.urls'))),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyec_inmobiliariaPilar/apps/contrato/models.py
from django.db import models
from apps.propiedad.models import Propiedad, Persona

# Create your models here.

class PropietarioPropiedad(models.Model):
    estados=(
        ('5','5%'),
        ('10','10%'),
        ('15','15%'),
        ('20','20%'),
        ('25','25%'),
        ('30','30%'),
    )

    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE, unique=True)
    propietario=models.ForeignKey(Persona,on_delete=models.CASCADE)
    condiciones = models.TextField()
    comision = models.CharField(max_length=5 ,choices=estados)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    fecha_alta=models.DateTimeField(auto_now_add=True)
    cancelacion = models.BooleanField(default=False)
    fecha_cancelacion = models.DateField(blank=True, null=True)

class InquilinoPropiedad(models.Model):
    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    inquilino=models.ForeignKey(Persona,on_delete=models.CASCADE)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()
    cant_personas=models.IntegerField()
    importe_total=models.DecimalField(max_digits=10,decimal_places=2)
    cancelacion = models.BooleanField(default=False)
    fecha_cancelacion = models.DateField(blank=True, null=True)

proyec_inmobiliariaPilar/apps/persona/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    #cod_persona=models.IntegerField(unique=True)
    
    provincia=models.CharField(max_length=20)
    localidad=models.CharField(max_length=20)
    barrio=models.CharField(max_length=20)
    calle=models.CharField(max_length=20)
    numero=models.CharField(max_length=5)
    telefono=models.CharField(max_length=13)
    mail=models.EmailField(max_length=30, unique=True)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    fecha_modificacion=models.DateTimeField(auto_now=True)
    desc_per=models.CharField(max_length=8)

    def __str__(self):
        if PersonaFisica.objects.filter(pk = self.pk).exists():
            persona = PersonaFisica.objects.get(pk = self.pk)
            return '{0},{1} -- {2}'.format(persona.nombre, persona.apellido, persona.cuil)
        if PersonaJuridica.objects.filter(pk = self.pk).exists():
            persona = PersonaJuridica.objects.get(pk = self.pk)
            return '{0} -- {1}'.format(persona.razon_social, persona.cuit)

class PersonaFisica(Persona):
    #CAMPOS PROPIOS DEL MODELO PERSONAFISICA 
    nombre=models.CharField(max_length=50)
    apellido = models.CharField(max_length=40)
    cuil=models.CharField(max_length=11,unique=True)

    def __str__(self):
        return '{0} -- {1}'.format(self.nombre, self.apellido)


class PersonaJuridica(Persona):
    #CAMPOS PROPIOS DEL MODELO PERSONAJURIDICA
    razon_social=models.CharField(max_length=50)
    cuit=models.CharField(max_length=11,unique=True)
    
    def __str__(self):
        return '{0} -- {1}'.format(self.razon_social, self.cuit)

proyec_inmobiliariaPilar/apps/propiedad/models.py
from django.db import models
from apps.persona.models import Persona

# Create your models here.

class Propiedad(models.Model):
    opc_tipo_alquiler=(
        ('DIARIO','Diario'),
        ('SEMANAL','Semanal'),
        ('MENSUAL','Mensual'),
    )
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    mts=models.CharField(max_length=20)
    mts_semicubiertos=models.CharField(max_length=10)
    capacidad=models.IntegerField()
    cant_ambientes=models.IntegerField()
    cochera=models.BooleanField()
    capacidad_cochera=models.IntegerField(blank=True, null=True)
    cant_banios=models.IntegerField()
    permite_cancelacion=models.BooleanField()
    tipo_alquiler=models.CharField(max_length=7,choices=opc_tipo_alquiler)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    precio=models.IntegerField()
    desc_prop=models.TextField()
    imagen=models.ImageField(upload_to='propiedad')
    tipo_propiedad=models.CharField(max_length=15, blank=False, null=False)
    estado_actual=models.CharField(max_length=16, choices=estados, default='disponible')
    zona=models.CharField(max_length=20,choices=zonas)


    def __str__(self):
        return 'Codigo Propiedad= %s   Tipo Alquiler= %s ' %(self.pk,self.tipo_alquiler)

class PropiedadCasa(Propiedad):
    #tipo_propiedad = 'casa'
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    patio=models.CharField(max_length=2,choices=opc)
    pileta=models.CharField(max_length=2,choices=opc)
    terraza=models.CharField(max_length=2,choices=opc)

class PropiedadDepto(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_depto=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='departamento', editable=False)
    frente=models.CharField(max_length=2,choices=opc)
    contrafrente=models.CharField(max_length=2,choices=opc)
    espacios_comunes=models.CharField(max_length=2,choices=opc)

class PropiedadHabitacion(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_hab=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='habitacion', editable=False)
    banio_individual=models.CharField(max_length=2,choices=opc)

class Oferta(models.Model):
    
    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    cod_oferta=models.CharField(unique=True,max_length=5)
    permite_cancelacion=models.BooleanField()
    #periodo_vigencia=models.CharField(max_length=5)
    fecha_inicio = models.DateField(auto_now_add=True)
    fecha_fin = models.DateField()
    fecha_solicitud=models.DateTimeField(auto_now_add=True)

class Estado(models.Model):

    propiedad=models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    fec_inicio=models.DateField(auto_now_add=True)
    fec_fin = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=20)
    band = models.BooleanField()

class FiltrarPropiedad(models.Model):
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    opc=(
        ('CASA','Casa'),
        ('DEPARTAMENTO','Departamento'),
        ('HABITACION','Habitacion'),
    )
    condicion = models.CharField(max_length=20,choices=estados, null=True, blank=True)
    tipo_propiedad = models.CharField(max_length=15,choices=opc, null=True, blank=True)
    zona = models.CharField(max_length=10 ,choices=zonas, null=True, blank=True)

proyec_inmobiliariaPilar/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html  lang="es" class="no-js"> 
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Inmobiliaria Pilar</title>
	<!-- Los iconos tipo Solid de Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
    <script src="https://kit.fontawesome.com/940f134d7b.js" crossorigin="anonymous"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,300' rel='stylesheet" type='text/css'>
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'base/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'base/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
	<!-- Superfish -->
	<link rel="stylesheet" href="{% static 'base/css/superfish.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'base/css/flexslider.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'base/css/magnific-popup.css' %}">
	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'base/css/bootstrap-datepicker.min.css' %}">
	<!-- CS Select -->
	<link rel="stylesheet" href="{% static 'base/css/cs-select.css' %}">
	<link rel="stylesheet" href="{% static 'base/css/cs-skin-border.css' %}">
	<link rel="stylesheet" href="{% static 'base/css/style.css' %}">
	<!-- Modernizr JS -->
    <script src="{% static 'base/js/modernizr-2.6.2.min.js' %}"></script>
    <!--HICHCHARTS para graficos estadisticos-->
    <script src = "https://code.highcharts.com/highcharts.src.js" > </script> 

</head>
<body>
    <div id="fh5co-wrapper">
        <div id="fh5co-page">
            <header id="fh5co-header-section" class="sticky-banner">
                <div class="container">
                    <div class="nav-header">
                        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                        <h1 id="fh5co-logo"><a href="http://127.0.0.1:8000/"><i class="icon-home"></i>INMOBILIARIA <span>PILAR</span></a></h1>
                        <!-- BARRA DE MENU -->
                        <nav id="fh5co-menu-wrap" role="navigation">
                            <ul class="sf-menu" id="fh5co-primary-menu">
                                <li><a href="{% url 'index' %}">Inicio</a></li>
                                <li><a href="{% url 'mostrar_ofertas' %}">Ofertas</a></li>
                                <li><a href="{% url 'busqueda' %}"><i class="fas fa-search"></i> Buscar <i class="fas fa-home"></i></a></li>
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'logout' %}">Salir</a></li>
                                <li><a href="">Activo: {{user.username}}</a></li>
                                {% endif%}

                            </ul>
                        </nav>
                    </div>
                </div>
            </header>
            {% if user.is_authenticated %}
            <div id="AdminMenu">
                <ul style="text-align: center">
                    {% if perms.propiedad.view_propiedad %}
                        <li style="display: inline;"><a href="{% url 'listado_propiedades' %}">Gestion Propiedades</a></li>
                    {% endif %}

                    {% if perms.propiedad.view_oferta %}
                    <li style="display: inline;"><a href="{% url 'listado_ofertas' %}">Gestion Ofertas</a></li>
                    {% endif %}

                    {% if perms.contrato.view_inquilinopropiedad %}
                        {% if perms.contrato.view_propietariopropiedad %}
                    <li style="display: inline;"><a href="{% url 'listado_contratos' %}">Gestion Contratos</a></li>
                        {% endif %}
                    {% endif %}
                    
                    {% if perms.persona.view_persona %}
                    <li style="display: inline;"><a href="{% url 'listado_personas' %}">Gestion Clientes</a></li>
                    {% endif %}

                    {% if perms.estadisticas.view_estadisticas %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Estadisticas
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: black;">
                            <a class="dropdown-item" href="{% url 'zona_menorAlquiler' %}" style="color: black;"> <p style="color: blanchedalmond;">Zona de Menos Alquiler</p></a>
                            <div class="dropdown-divider" ></div>
                            <a class="dropdown-item" href="{% url 'porcentaje_ocupacion' %}" style="color: black;"> <p style="color: blanchedalmond;"> Porcentaje de Ocupacion</p> </a>
                            <div class="dropdown-divider" ></div>
                            <a class="dropdown-item" href="{% url 'preferencia_zona_tipoPropiedad' %}" style="color: black;"> <p style="color: blanchedalmond">Zona y Tipo de Propiedad</p>  </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'preferencia_zona_tipoAlquiler' %}" style="color: black;"> <p style="color: blanchedalmond;">Zona y Tipo de Alquiler</p>  </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'tiempoSinAlquilar' %}" style="color: black;"> <p style="color: blanchedalmond;">Propiedades y Tiempo Sin Alquilar</p>  </a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div> 
            {% endif %}

            <style>
                div#AdminMenu ul li{
                    display: inline;
                    margin-left: 1em;
                    margin-right: 1em;
                }
                div#AdminMenu{
                    width: 100%;
                    background-color: black;
                    padding-top: 1em;
                    padding-bottom: 0.1em;
                    margin-bottom: 1em;
                }
                div#AdminMenu ul li a{
                    color: blanchedalmond;
                }
                div.dropdown-menu a{
                    color: blanchedalmond;
                }
                div.dropdown-menu{
                    width: 5em;
                }
                a.dropdown-item{
                    margin-bottom: 3em;
                    background-color: black;
                }
            </style>
            
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert" style="text-align: center;">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success" role="alert" style="text-align: center;">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <!-- el block contenido servira para diferentes paginas dinamicas-->
            {% block contenido %}
                
            {% endblock %}
            
            <!-- Pie de pagina -->
            <footer>
                <div id="footer">
                    <div class="container">
                        <div class="row row-bottom-padded-md">
                            <div class="col-md-12">
                                <h3  style="text-align: center;" class="section-title">Sobre Inmobiliaria Pilar</h3>
                                <p style="text-align: center;">Esta pagina web trata sobre el alquiler de diferentes tipo de propiedades.</p>
                            </div>   
                        </div>
                        <div  class="row">
                            <div class="col-md-12">
                                <p style="text-align: center;" class="fh5co-social-icons">
                                    <a href="#"><i class="icon-twitter2"></i></a>
                                    <a href="#"><i class="icon-facebook2"></i></a>
                                    <a href="#"><i class="icon-instagram"></i></a>
                                    <a href="#"><i class="icon-dribbble2"></i></a>
                                    <a href="#"><i class="icon-youtube"></i></a>
                                </p>
                                <p style="text-align: center;">Copyright 2020. Todos los derechos reservados. Programacion III </p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <!-- END fh5co-page -->
    </div>
    <!--FIN ULTIMO DIV -->

    <!-- jQuery -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <!-- jQuery Easing -->
    <script src="{% static 'base/js/jquery.easing.1.3.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <!-- Waypoints -->
    <script src="{% static 'base/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'base/js/sticky.js' %}"></script>
    <!-- Superfish -->
    <script src="{% static 'base/js/hoverIntent.js' %}"></script>
    <script src="{% static 'base/js/superfish.js' %}"></script>
    <!-- Flexslider -->
    <script src="{% static 'base/js/jquery.flexslider-min.js' %}"></script>
    <!-- Date Picker -->
    <script src="{% static 'base/js/bootstrap-datepicker.min.js' %}"></script>
    <!-- CS Select -->
    <script src="{% static 'base/js/classie.js' %}"></script>
    <script src="{% static 'base/js/selectFx.js' %}"></script>
    <!-- Main JS -->
    <script src="{% static 'base/js/main.js' %}"></script>
</body>
</html>