proyec_inmobiliariaPilar/apps/propiedad/urls.py
from django.urls import path
from apps.propiedad import views

urlpatterns = [
    path('listadoPropiedades/', views.ListadoPropiedades,name='listado_propiedades'),
    path('casa/',views.NuevaPropiedadCasa, name='nueva_casa'),
    path('dpto/',views.NuevaPropiedadDpto, name='nuevo_dpto'),
    path('habitacion/',views.NuevaPropiedadHabitacion, name='nueva_habitacion'),
    path('modificar/<id>/',views.ModificarPropiedad, name='modificar_propiedad'),
    path('eliminar/<id>/',views.EliminarPropiedad, name='eliminar_propiedad'),
    path('nuevaOferta/',views.NuevaOferta, name='nueva_oferta'),
    path('Ofertas/',views.MostrarOfertas, name='mostrar_ofertas'),
    path('listadoOfertas/',views.ListarOfertas, name='listado_ofertas'),
    path('modificarOferta/<id>/',views.ModificarOferta, name='modificar_oferta'),
    path('eliminarOferta/<id>/',views.EliminarOferta, name='eliminar_oferta'),
    path('detallesPropiedad/<id>/',views.detallePropiedad, name='detalles_propiedad'),
    path('eliminarPropiedad/<id>/',views.ConfirmarPropiedad, name='confirmar_propiedad'),
    path('mostrarPropiedad/<id>/',views.MostrarPropiedad, name='mostrar_propiedad'),
]

proyec_inmobiliariaPilar/pilar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('apps.inicio.urls'))),
    path('clientes/', include(('apps.persona.urls'))),
    path('propiedad/', include(('apps.propiedad.urls'))),
    path('busqueda/', include(('apps.busqueda.urls'))),
    path('contrato/', include(('apps.contrato.urls'))),
    path('contacto/', include(('apps.contacto.urls'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estadisticas/', include(('apps.estadisticas.urls'))),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyec_inmobiliariaPilar/apps/propiedad/models.py
from django.db import models
from apps.persona.models import Persona

# Create your models here.

class Propiedad(models.Model):
    opc_tipo_alquiler=(
        ('DIARIO','Diario'),
        ('SEMANAL','Semanal'),
        ('MENSUAL','Mensual'),
    )
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    mts=models.CharField(max_length=20)
    mts_semicubiertos=models.CharField(max_length=10)
    capacidad=models.IntegerField()
    cant_ambientes=models.IntegerField()
    cochera=models.BooleanField()
    capacidad_cochera=models.IntegerField(blank=True, null=True)
    cant_banios=models.IntegerField()
    permite_cancelacion=models.BooleanField()
    tipo_alquiler=models.CharField(max_length=7,choices=opc_tipo_alquiler)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    precio=models.IntegerField()
    desc_prop=models.TextField()
    imagen=models.ImageField(upload_to='propiedad')
    tipo_propiedad=models.CharField(max_length=15, blank=False, null=False)
    estado_actual=models.CharField(max_length=16, choices=estados, default='disponible')
    zona=models.CharField(max_length=20,choices=zonas)


    def __str__(self):
        return 'Codigo Propiedad= %s   Tipo Alquiler= %s ' %(self.pk,self.tipo_alquiler)

class PropiedadCasa(Propiedad):
    #tipo_propiedad = 'casa'
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    patio=models.CharField(max_length=2,choices=opc)
    pileta=models.CharField(max_length=2,choices=opc)
    terraza=models.CharField(max_length=2,choices=opc)

class PropiedadDepto(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_depto=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='departamento', editable=False)
    frente=models.CharField(max_length=2,choices=opc)
    contrafrente=models.CharField(max_length=2,choices=opc)
    espacios_comunes=models.CharField(max_length=2,choices=opc)

class PropiedadHabitacion(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_hab=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='habitacion', editable=False)
    banio_individual=models.CharField(max_length=2,choices=opc)

class Oferta(models.Model):
    
    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    cod_oferta=models.CharField(unique=True,max_length=5)
    permite_cancelacion=models.BooleanField()
    #periodo_vigencia=models.CharField(max_length=5)
    fecha_inicio = models.DateField(auto_now_add=True)
    fecha_fin = models.DateField()
    fecha_solicitud=models.DateTimeField(auto_now_add=True)

class Estado(models.Model):

    propiedad=models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    fec_inicio=models.DateField(auto_now_add=True)
    fec_fin = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=20)
    band = models.BooleanField()

class FiltrarPropiedad(models.Model):
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    opc=(
        ('CASA','Casa'),
        ('DEPARTAMENTO','Departamento'),
        ('HABITACION','Habitacion'),
    )
    condicion = models.CharField(max_length=20,choices=estados, null=True, blank=True)
    tipo_propiedad = models.CharField(max_length=15,choices=opc, null=True, blank=True)
    zona = models.CharField(max_length=10 ,choices=zonas, null=True, blank=True)

proyec_inmobiliariaPilar/apps/propiedad/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from apps.contrato.models import InquilinoPropiedad, PropietarioPropiedad
from .models import Propiedad, PropiedadCasa, PropiedadDepto, PropiedadHabitacion, Oferta, Estado
from .forms import PropiedadCasaForm,PropiedadDptoForm,PropiedadHabitacionForm, OfertaForm, EstadoForm, FiltrarPropiedadForm, FiltrarOfertaForm

# Create your views here.

@login_required
def ListadoPropiedades(request):
    if request.user.has_perms('propiedad.can_view_propiedad'):
        propiedades = Propiedad.objects.all()
        form = FiltrarPropiedadForm()
        if request.method == 'POST':
            condicion= request.POST.get('condicion')
            tipo_propiedad = request.POST.get('tipo_propiedad')
            zona = request.POST.get('zona')
            if condicion != "":
                propiedades = propiedades.filter(estado_actual=condicion)    
            if tipo_propiedad != "":
                propiedades = propiedades.filter(tipo_propiedad=tipo_propiedad)
            if zona != "":    
                propiedades = propiedades.filter(zona= zona)

        return render(request,'propiedad/lista_propiedades.html',{'propiedades':propiedades, 'form':form})
    else:
        messages.error(request,'No tienes permisos para visualizar las PROPIEDADES')
        return redirect(to = "index")



@login_required
def detallePropiedad(request,id):
    if request.user.has_perms('propiedad.can_view_propiedad'):
        pro = Propiedad.objects.get(pk=id)
        return render(request,'propiedad/detalles_propiedad.html',{'pro':pro})
    else:
        messages.error(request,'No tienes permiso para visualizar PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadCasa(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadCasaForm()
        }
        if request.method == 'POST':
            f = PropiedadCasaForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad='CASA'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper()
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                casa = Propiedad.objects.last()
                GenerarEstado(casa)
                mensaje = 'Se agrego una nueva casa al sistema CASA ID: {0}'.format(casa.id)
                messages.success(request,mensaje)
                data = {
                    "id": casa.id,
                    "mts": casa.mts,
                    "mts_semicubiertos": casa.mts_semicubiertos,
                    "patio": casa.propiedadcasa.patio ,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f
                
        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:
        messages.error(request,'No tienes permiso para ingresar PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadDpto(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadDptoForm()
        }
        if request.method == 'POST':
            f = PropiedadDptoForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad ='DEPARTAMENTO'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper() 
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                dpto = Propiedad.objects.last()
                GenerarEstado(dpto)
                mensaje = 'Se agrego una nuevo DEPARTAMENTO al sistema DEPARTAMENTO ID: {0}'.format(dpto.pk)
                messages.success(request,mensaje)
                data = {
                    "id": dpto.id,
                    "mts": dpto.mts,
                    "mts_semicubiertos": dpto.mts_semicubiertos,
                    "patio": dpto.zona,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f

        return render(request, 'propiedad/nueva_propiedad.html', data )
    else:
        messages.error(request,'No tienes permiso para el ingreso de PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadHabitacion(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadHabitacionForm()
        }
        if request.method == 'POST':
            f = PropiedadHabitacionForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad='HABITACION'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper() 
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                habitacion = Propiedad.objects.last()
                GenerarEstado(habitacion)
                mensaje = 'Se agrego una nuevo DEPARTAMENTO al sistema DEPARTAMENTO ID: {0}'.format(habitacion.pk)
                messages.success(request,mensaje)
                data = {
                    "id": habitacion.id,
                    "mts": habitacion.mts,
                    "mts_semicubiertos": habitacion.mts_semicubiertos,
                    "patio": habitacion.zona,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f

        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:
        messages.error(request,'No tienes permiso para el ingreso de PROPIEDADES')
        return redirect(to = "index")



@login_required
def ModificarPropiedad(request,id):
    if request.user.has_perms('propiedad.can_change_propiedad'):
        propiedad = Propiedad.objects.get(pk=id)
        if InquilinoPropiedad.objects.filter(propiedad = propiedad).exists():
            messages.error(request,'NO SE PUEDE MODIFICAR UNA PROPIEDAD QUE SE ENCUENTRA EN CONTRATO')
            return redirect(to='listado_propiedades')
        if PropietarioPropiedad.objects.filter(propiedad = propiedad).exists():
            messages.error(request,'NO SE PUEDE MODIFICAR UNA PROPIEDAD QUE SE ENCUENTRA EN CONTRATO')
            return redirect(to='listado_propiedades')
        tipo = propiedad.tipo_propiedad
        data = {
            "mensaje" : 'no se puede'
        }
        if tipo == 'CASA':
            casa = PropiedadCasa.objects.get(pk=id)
            cambio = casa.estado_actual
            data = {
                "form": PropiedadCasaForm(instance=propiedad)
            }
            if request.method == 'POST':
                formulario = PropiedadCasaForm(data=request.POST,files=request.FILES, instance=casa)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadCasaForm(instance=casa),
                    }
                    casa = Propiedad.objects.get(pk=id)
                    if casa.estado_actual != cambio:
                        GenerarEstado(casa)
                data["form"] = formulario

        elif tipo == 'DEPARTAMENTO':
            dpto = PropiedadDepto.objects.get(pk=id)
            cambio = dpto.estado_actual
            data = {
                "form": PropiedadDptoForm(instance=dpto)
            }
            if request.method == 'POST':
                formulario = PropiedadDptoForm(data=request.POST,files=request.FILES, instance=dpto)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadDptoForm(instance=dpto),
                    }  
                    dpto = Propiedad.objects.get(pk=id)
                    if dpto.estado_actual != cambio:
                        GenerarEstado(dpto)
                data["form"] = formulario

        elif tipo =='HABITACION':
            habitacion = PropiedadHabitacion.objects.get(pk=id)
            cambio = habitacion.estado_actual
            data = {
                "form": PropiedadHabitacionForm(instance=habitacion)
            }
            if request.method == 'POST':
                formulario = PropiedadHabitacionForm(data=request.POST,files=request.FILES,instance=habitacion)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadHabitacionForm(instance=habitacion),
                    }
                    habitacion = Propiedad.objects.get(pk=id)
                    if habitacion.estado_actual != cambio:
                        GenerarEstado(habitacion)
                data["form"] = formulario

        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:  
        messages.error(request,'No tienes permiso para modificar PROPIEDADES')
        return redirect(to = "index")



@login_required
def EliminarPropiedad(request, id):
    if request.user.has_perms('propiedad.can_delete_propiedad'):
        if PropiedadCasa.objects.filter(pk=id).exists():
            propiedad = PropiedadCasa.objects.get(pk=id)

proyec_inmobiliariaPilar/apps/propiedad/templates/oferta/listado_ofertas.html
{% extends "base/base.html" %}

{% load static %}

{% block contenido %}

<style>
    div#addPropiedades{
        border: 1px solid black;
        padding: 2em;
        text-align: center;
        margin-bottom: 2em;
    }
    div#addPropiedades a{
        padding: 1em;
        color: #ffffff;
        margin: 1em;
        background-color: darkblue;
    }
    table a{
        margin-right: 1em;
        background-color: black;
    }
</style>

<h1 style="text-align: center;">LISTADO DE OFERTAS</h1>
{% if perms.oferta.add_oferta %}
<div id="addPropiedades">
    <a href="{% url 'nueva_oferta' %}">NUEVA OFERTA</a>
</div>
{% endif %}

<div class="container">

    <div class="row">

        <div class="col-sm-2" style="border: 1px solid black;">

            <form action= "" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="BUSCAR">
            </form>

        </div>

        <div class="col-sm-10">

            <table class="table-bordered" style="width: 100%;">
                <thead class="thead-dark" style="background-color: black;">
                <tr style="color: blanchedalmond; text-align: center;">
                    <th scope="col">ID</th>
                    <th scope="col">PROPIEDAD</th>
                    <th scope="col">COD OFERTA</th>
                    <th scope="col">FECHA INICIO</th>
                    <th scope="col">FECHA FIN</th>
                    <th scope="col">OPCIONES</th>
                </tr>
                </thead>
                {% for oferta in ofertas %}
                <tbody>
                <tr>
                    <th scope="row">{{oferta.propiedad.id}}</th>
                    <td>{{oferta.propiedad.id}}</td>
                    <td>{{oferta.cod_oferta}}</td>
                    <td>{{oferta.fecha_inicio}}</td>
                    <td>{{oferta.fecha_fin}}</td>
                    <td>
                        {% if perms.oferta.change_oferta %}
                        <a href="{% url 'modificar_oferta' oferta.id %}">Modificar</a> 
                        {% endif %}
            
                        {% if perms.oferta.delete_oferta %}
                        <a href="{% url 'eliminar_oferta' oferta.id %}">Eliminar</a>
                        {% endif %}
                    </td>
                </tr>
                </tbody>
                {% endfor %}
            </table>

        </div>

    </div>


</div>


{% endblock %}

proyec_inmobiliariaPilar/apps/propiedad/templates/oferta/nueva_oferta.html
{% extends "base/base.html" %}

{% load static %}

{% block contenido %}

<style>
    div.container{

        margin-bottom: 1em;
        margin-top: 1em;

    }

    div.form-group.row{

        margin-top: 1em;
        margin-left: 1em;
        margin-right: 1em;
        vertical-align: middle;

    }

    div.input-field select{
        
        display: block;
        margin: 0;
        width: 100%;
    }
</style>

<div class="container" style="background-image: url({% static 'base/fondo-formulario.jpg' %});">
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% for field in form %}

        <div class="form-group row">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label" style="color: #fff;">{{field.label}}</label>
            <div class="col-sm-10">
                {{field}}{{field.errors}}
            </div>
        </div>
        

    {% endfor %}
        <div class="input-field" style="padding: 3em; text-align: center;" >
            <input class="btn-primary" type="submit" name="ENVIAR">
            <input class="btn-primary" type="reset" name="RESET">
        </div>
        <h3>{{mensaje}}</h3>

    </form>
</div>

{% endblock %}

proyec_inmobiliariaPilar/apps/propiedad/templates/oferta/ofertas.html
{% extends 'base/base.html' %}

{% load static %}

{% block contenido %}
        <!-- end:header-top -->
		<div id="fh5co-properties" class="fh5co-section-gray">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
						<h3>OFERTAS DE PROPIEDADES</h3>
						<p>Propiedades que se encuentran actualmente en oferta dentro del sistema</p>
					</div>
                </div>
                {% for oferta in ofertas %}
				<div class="row">
					<div class="col-md-4 animate-box">
						<div class="property">
							<a href="#" class="fh5co-property" style="background-image: url({{oferta.propiedad.imagen.url}});">
                                <span class="status">Oferta</span>
								<ul class="list-details">
									<li>Metros:{{oferta.propiedad.mts}}mts<li>
									<li>Ambientes:{{oferta.propiedad.cant_ambientes}}</li>
									<li>Baños:{{oferta.propiedad.cant_banios}}</li>
									{% if oferta.propiedad.cochera %}
									<li>Garage:{{oferta.propiedad.capacidad_cochera}}</li>
									{% endif %}
								</ul>
							</a>
							<div class="property-details">
								<h3>{{servicio.titulo}}</h3>
								<span class="price">{{oferta.propiedad.precio}}</span>
								<p>{{oferta.propiedad.desc_prop}}</p>
								<span class="address"><i class="icon-map"></i>ZONA: {{oferta.propiedad.zona}}</span>
							</div>
						</div>
                    </div>
                {% endfor %}
				</div>
			</div>
		</div>
{% endblock %}