proyec_inmobiliariaPilar/apps/propiedad/urls.py
from django.urls import path
from apps.propiedad import views

urlpatterns = [
    path('listadoPropiedades/', views.ListadoPropiedades,name='listado_propiedades'),
    path('casa/',views.NuevaPropiedadCasa, name='nueva_casa'),
    path('dpto/',views.NuevaPropiedadDpto, name='nuevo_dpto'),
    path('habitacion/',views.NuevaPropiedadHabitacion, name='nueva_habitacion'),
    path('modificar/<id>/',views.ModificarPropiedad, name='modificar_propiedad'),
    path('eliminar/<id>/',views.EliminarPropiedad, name='eliminar_propiedad'),
    path('nuevaOferta/',views.NuevaOferta, name='nueva_oferta'),
    path('Ofertas/',views.MostrarOfertas, name='mostrar_ofertas'),
    path('listadoOfertas/',views.ListarOfertas, name='listado_ofertas'),
    path('modificarOferta/<id>/',views.ModificarOferta, name='modificar_oferta'),
    path('eliminarOferta/<id>/',views.EliminarOferta, name='eliminar_oferta'),
    path('detallesPropiedad/<id>/',views.detallePropiedad, name='detalles_propiedad'),
    path('eliminarPropiedad/<id>/',views.ConfirmarPropiedad, name='confirmar_propiedad'),
    path('mostrarPropiedad/<id>/',views.MostrarPropiedad, name='mostrar_propiedad'),
]

proyec_inmobiliariaPilar/pilar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('apps.inicio.urls'))),
    path('clientes/', include(('apps.persona.urls'))),
    path('propiedad/', include(('apps.propiedad.urls'))),
    path('busqueda/', include(('apps.busqueda.urls'))),
    path('contrato/', include(('apps.contrato.urls'))),
    path('contacto/', include(('apps.contacto.urls'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estadisticas/', include(('apps.estadisticas.urls'))),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyec_inmobiliariaPilar/apps/propiedad/models.py
from django.db import models
from apps.persona.models import Persona

# Create your models here.

class Propiedad(models.Model):
    opc_tipo_alquiler=(
        ('DIARIO','Diario'),
        ('SEMANAL','Semanal'),
        ('MENSUAL','Mensual'),
    )
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    mts=models.CharField(max_length=20)
    mts_semicubiertos=models.CharField(max_length=10)
    capacidad=models.IntegerField()
    cant_ambientes=models.IntegerField()
    cochera=models.BooleanField()
    capacidad_cochera=models.IntegerField(blank=True, null=True)
    cant_banios=models.IntegerField()
    permite_cancelacion=models.BooleanField()
    tipo_alquiler=models.CharField(max_length=7,choices=opc_tipo_alquiler)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    precio=models.IntegerField()
    desc_prop=models.TextField()
    imagen=models.ImageField(upload_to='propiedad')
    tipo_propiedad=models.CharField(max_length=15, blank=False, null=False)
    estado_actual=models.CharField(max_length=16, choices=estados, default='disponible')
    zona=models.CharField(max_length=20,choices=zonas)


    def __str__(self):
        return 'Codigo Propiedad= %s   Tipo Alquiler= %s ' %(self.pk,self.tipo_alquiler)

class PropiedadCasa(Propiedad):
    #tipo_propiedad = 'casa'
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    patio=models.CharField(max_length=2,choices=opc)
    pileta=models.CharField(max_length=2,choices=opc)
    terraza=models.CharField(max_length=2,choices=opc)

class PropiedadDepto(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_depto=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='departamento', editable=False)
    frente=models.CharField(max_length=2,choices=opc)
    contrafrente=models.CharField(max_length=2,choices=opc)
    espacios_comunes=models.CharField(max_length=2,choices=opc)

class PropiedadHabitacion(Propiedad):
    opc=(
        ('SI','Si'),
        ('NO','No'),
    )
    #prop_hab=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    #tipo_propiedad=models.CharField(max_length=15, default='habitacion', editable=False)
    banio_individual=models.CharField(max_length=2,choices=opc)

class Oferta(models.Model):
    
    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    cod_oferta=models.CharField(unique=True,max_length=5)
    permite_cancelacion=models.BooleanField()
    #periodo_vigencia=models.CharField(max_length=5)
    fecha_inicio = models.DateField(auto_now_add=True)
    fecha_fin = models.DateField()
    fecha_solicitud=models.DateTimeField(auto_now_add=True)

class Estado(models.Model):

    propiedad=models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    fec_inicio=models.DateField(auto_now_add=True)
    fec_fin = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=20)
    band = models.BooleanField()

class FiltrarPropiedad(models.Model):
    zonas=(
        ('NORTE','Norte'),
        ('SUR','Sur'),
        ('ESTE','Este'),
        ('OESTE','Oeste'),
    )
    estados=(
        ('DISPONIBLE','Disponible'),
        ('OCUPADO','Ocupado'),
        ('EN MANTENIMIENTO','En Mantenimiento'),
    )
    opc=(
        ('CASA','Casa'),
        ('DEPARTAMENTO','Departamento'),
        ('HABITACION','Habitacion'),
    )
    condicion = models.CharField(max_length=20,choices=estados, null=True, blank=True)
    tipo_propiedad = models.CharField(max_length=15,choices=opc, null=True, blank=True)
    zona = models.CharField(max_length=10 ,choices=zonas, null=True, blank=True)

proyec_inmobiliariaPilar/apps/propiedad/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from apps.contrato.models import InquilinoPropiedad, PropietarioPropiedad
from .models import Propiedad, PropiedadCasa, PropiedadDepto, PropiedadHabitacion, Oferta, Estado
from .forms import PropiedadCasaForm,PropiedadDptoForm,PropiedadHabitacionForm, OfertaForm, EstadoForm, FiltrarPropiedadForm, FiltrarOfertaForm

# Create your views here.

@login_required
def ListadoPropiedades(request):
    if request.user.has_perms('propiedad.can_view_propiedad'):
        propiedades = Propiedad.objects.all()
        form = FiltrarPropiedadForm()
        if request.method == 'POST':
            condicion= request.POST.get('condicion')
            tipo_propiedad = request.POST.get('tipo_propiedad')
            zona = request.POST.get('zona')
            if condicion != "":
                propiedades = propiedades.filter(estado_actual=condicion)    
            if tipo_propiedad != "":
                propiedades = propiedades.filter(tipo_propiedad=tipo_propiedad)
            if zona != "":    
                propiedades = propiedades.filter(zona= zona)

        return render(request,'propiedad/lista_propiedades.html',{'propiedades':propiedades, 'form':form})
    else:
        messages.error(request,'No tienes permisos para visualizar las PROPIEDADES')
        return redirect(to = "index")



@login_required
def detallePropiedad(request,id):
    if request.user.has_perms('propiedad.can_view_propiedad'):
        pro = Propiedad.objects.get(pk=id)
        return render(request,'propiedad/detalles_propiedad.html',{'pro':pro})
    else:
        messages.error(request,'No tienes permiso para visualizar PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadCasa(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadCasaForm()
        }
        if request.method == 'POST':
            f = PropiedadCasaForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad='CASA'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper()
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                casa = Propiedad.objects.last()
                GenerarEstado(casa)
                mensaje = 'Se agrego una nueva casa al sistema CASA ID: {0}'.format(casa.id)
                messages.success(request,mensaje)
                data = {
                    "id": casa.id,
                    "mts": casa.mts,
                    "mts_semicubiertos": casa.mts_semicubiertos,
                    "patio": casa.propiedadcasa.patio ,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f
                
        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:
        messages.error(request,'No tienes permiso para ingresar PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadDpto(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadDptoForm()
        }
        if request.method == 'POST':
            f = PropiedadDptoForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad ='DEPARTAMENTO'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper() 
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                dpto = Propiedad.objects.last()
                GenerarEstado(dpto)
                mensaje = 'Se agrego una nuevo DEPARTAMENTO al sistema DEPARTAMENTO ID: {0}'.format(dpto.pk)
                messages.success(request,mensaje)
                data = {
                    "id": dpto.id,
                    "mts": dpto.mts,
                    "mts_semicubiertos": dpto.mts_semicubiertos,
                    "patio": dpto.zona,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f

        return render(request, 'propiedad/nueva_propiedad.html', data )
    else:
        messages.error(request,'No tienes permiso para el ingreso de PROPIEDADES')
        return redirect(to = "index")



@login_required
def NuevaPropiedadHabitacion(request):
    if request.user.has_perms('propiedad.can_add_propiedad'):
        data = {
            "form" : PropiedadHabitacionForm()
        }
        if request.method == 'POST':
            f = PropiedadHabitacionForm(request.POST,request.FILES)
            if f.is_valid():
                form = f.save(commit=False)
                form.tipo_propiedad='HABITACION'
                form.desc_prop = form.desc_prop.upper()
                form.tipo_propiedad = form.tipo_propiedad.upper() 
                form.zona = form.zona.upper()
                form.estado_actual = form.estado_actual.upper()
                form.save()
                habitacion = Propiedad.objects.last()
                GenerarEstado(habitacion)
                mensaje = 'Se agrego una nuevo DEPARTAMENTO al sistema DEPARTAMENTO ID: {0}'.format(habitacion.pk)
                messages.success(request,mensaje)
                data = {
                    "id": habitacion.id,
                    "mts": habitacion.mts,
                    "mts_semicubiertos": habitacion.mts_semicubiertos,
                    "patio": habitacion.zona,
                }
                return render(request, 'propiedad/mostrar_propiedad.html', data)
            data["form"] = f

        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:
        messages.error(request,'No tienes permiso para el ingreso de PROPIEDADES')
        return redirect(to = "index")



@login_required
def ModificarPropiedad(request,id):
    if request.user.has_perms('propiedad.can_change_propiedad'):
        propiedad = Propiedad.objects.get(pk=id)
        if InquilinoPropiedad.objects.filter(propiedad = propiedad).exists():
            messages.error(request,'NO SE PUEDE MODIFICAR UNA PROPIEDAD QUE SE ENCUENTRA EN CONTRATO')
            return redirect(to='listado_propiedades')
        if PropietarioPropiedad.objects.filter(propiedad = propiedad).exists():
            messages.error(request,'NO SE PUEDE MODIFICAR UNA PROPIEDAD QUE SE ENCUENTRA EN CONTRATO')
            return redirect(to='listado_propiedades')
        tipo = propiedad.tipo_propiedad
        data = {
            "mensaje" : 'no se puede'
        }
        if tipo == 'CASA':
            casa = PropiedadCasa.objects.get(pk=id)
            cambio = casa.estado_actual
            data = {
                "form": PropiedadCasaForm(instance=propiedad)
            }
            if request.method == 'POST':
                formulario = PropiedadCasaForm(data=request.POST,files=request.FILES, instance=casa)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadCasaForm(instance=casa),
                    }
                    casa = Propiedad.objects.get(pk=id)
                    if casa.estado_actual != cambio:
                        GenerarEstado(casa)
                data["form"] = formulario

        elif tipo == 'DEPARTAMENTO':
            dpto = PropiedadDepto.objects.get(pk=id)
            cambio = dpto.estado_actual
            data = {
                "form": PropiedadDptoForm(instance=dpto)
            }
            if request.method == 'POST':
                formulario = PropiedadDptoForm(data=request.POST,files=request.FILES, instance=dpto)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadDptoForm(instance=dpto),
                    }  
                    dpto = Propiedad.objects.get(pk=id)
                    if dpto.estado_actual != cambio:
                        GenerarEstado(dpto)
                data["form"] = formulario

        elif tipo =='HABITACION':
            habitacion = PropiedadHabitacion.objects.get(pk=id)
            cambio = habitacion.estado_actual
            data = {
                "form": PropiedadHabitacionForm(instance=habitacion)
            }
            if request.method == 'POST':
                formulario = PropiedadHabitacionForm(data=request.POST,files=request.FILES,instance=habitacion)
                if formulario.is_valid():
                    formulario.save()
                    data={
                        "mensaje":'guardado correctamente',
                        "form": PropiedadHabitacionForm(instance=habitacion),
                    }
                    habitacion = Propiedad.objects.get(pk=id)
                    if habitacion.estado_actual != cambio:
                        GenerarEstado(habitacion)
                data["form"] = formulario

        return render(request, 'propiedad/nueva_propiedad.html', data)
    else:  
        messages.error(request,'No tienes permiso para modificar PROPIEDADES')
        return redirect(to = "index")



@login_required
def EliminarPropiedad(request, id):
    if request.user.has_perms('propiedad.can_delete_propiedad'):
        if PropiedadCasa.objects.filter(pk=id).exists():
            propiedad = PropiedadCasa.objects.get(pk=id)

proyec_inmobiliariaPilar/apps/propiedad/templates/propiedad/detalles_propiedad.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}

    <!--MOSTRAMOS TODAS LAS PROPIEDADES DEBAJO DEL CARRUSEL DE OFERTAS-->
    {% if pro %}
    <section>
        <div id="fh5co-popular-properties" class="fh5co-section-gray">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
                        <h3 style="color: black; "><strong>DETALLES DE LA PROPIEDAD</strong> </h3>
                    </div>
                </div>  
                
                <div class="row">
                    <img src="{{pro.imagen.url}}" style="width: 100%; height: 100%;" ><br><br>
                    <h1 style="color: black;"><strong>
                        {{pro.tipo_propiedad|upper}} · {{pro.mts|upper}}m<sup>2</sup> · {{pro.cant_ambientes|upper}} dormitorios · {{pro.cant_banios|upper}} baño/s 
                    </strong></h1> 
                    <div class="Adminn">
                        <ul style="text-align: left">
                            <li style="display: inline;"><i class='fas fa-expand-arrows-alt'></i> {{pro.mts|upper}}m<sup>2</sup> cubiertos</li>
                            <li style="display: inline;"><i class='fas fa-users'></i> {{pro.capacidad|upper}} personas</li>
                            <li style="display: inline;"><i class='fas fa-bed'></i> {{pro.cant_ambientes|upper}} dormitorios</li>
                            <li style="display: inline;"><i class="fas fa-bath"></i> {{pro.cant_banios|upper}} baño/s</li>
                            {% if pro.cochera == True %}
                            <li style="display: inline;"><i class='fas fa-car'></i> {{pro.capacidad_cochera}}</li>
                            {% endif%}

                            <li style="display: inline;"> 
                                {% if pro.estado_actual == 'DISPONIBLE' %}
                                <i class="fas fa-check-circle" style="color: greenyellow;"></i> {{pro.estado_actual|upper}}
                                {% else %}
                                <i class="fas fa-times-circle" style="color: red;"></i> {{pro.estado_actual|upper}}
                                {% endif %}
                                </li>
                                {% if pro.oferta.cod_oferta %}
                                <li style="display: inline;"><i class='far fa-money-bill-alt'></i> EN OFERTA</li>
                                {% endif %}
                            


                            {% if pro.oferta.cod_oferta %}
                            <li style="display: inline;"><i class='far fa-money-bill-alt'></i> EN OFERTA</li>
                            {% endif %}
                            
                        </ul>
                    </div>
                    <div style="border-style: solid;border-width: 1px;">
                        <h2 style="color: black;margin: 20px;"><strong><u>Todos los detalles de la propiedad:</u> </strong></h2>
                        <p style="color: black;margin: 20px;">
                            {{pro.desc_prop}}
                            <ul id="detalles" style="list-style-type: none;">
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Codigo Propiedad: </u></strong>  {{pro.id}} </li>
                                {% if pro.oferta.cod_oferta %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Codigo Oferta: </u></strong>  {{pro.oferta.cod_oferta}}</li>
                                {% endif %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Tipo Propiedad: </u></strong>  {{pro.tipo_propiedad|capfirst}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Tipo Alquiler: </u></strong>  {{pro.tipo_alquiler|capfirst}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Estado: </u></strong>  {{pro.estado_actual|capfirst}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> M<sup>2</sup> Cubiertos: </u></strong>  {{pro.mts}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> M<sup>2</sup> Semicubiertos: </u></strong>  {{pro.mts_semicubiertos}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Capacidad: </u></strong>  {{pro.capacidad}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Cantidad de Dormitorios: </u></strong>  {{pro.cant_ambientes}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Cantidad de Baños: </u></strong>   {{pro.cant_banios}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Fecha Alta: </u></strong>  {{pro.fecha_alta}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Precio: </u></strong>  ${{pro.precio}}</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Zona: </u></strong>  {{pro.zona|capfirst}}</li>
                                {% if pro.permite_cancelacion == True %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Permite Cancelacion: </u></strong>  Si </li>
                                {% else %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Permite Cancelacion: </u></strong>  No </li>
                                {% endif %}
                                {% if pro.cochera == True %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Cochera: </u></strong>  Si</li>
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Capacidad Cochera: </u></strong>  {{pro.capacidad_cochera}}</li>
                                {% else %}
                                <li ><i class='far fa-thumbs-up'></i> <strong><u> Cochera: </u></strong>  No</li>
                                {% endif %}

                            </ul>
                        </p>
                    </div><br><br>
                    <div style="text-align: center;">
                        
                        {% if pro.estado_actual == 'DISPONIBLE' %}
                        <button type="button" class="btn btn-danger" ><a href="{% url 'contacto' %}" style="color: black;"><strong><i style="font-size: 20px;" class='far fa-handshake'></i> Contactar para Alquilar</strong> </a></button>
                        {% else %}
                        <button type="button" class="btn btn-danger" disabled><strong><i style="font-size: 20px;" class='far fa-handshake'></i> Contactar para Alquilar</strong></button>
                        {% endif %}
                        
                    </div>
                    <style>
                        #detalles li {
                            color: black;
                        }
                        div.Adminn ul li{
                            display: inline;
                            margin-left: 1em;
                            margin-right: 1em;
                            color: black;
                        }
                        div.Adminn{
                            width: 100%;
                            background-color: whitesmoke;
                            padding-top: 1em;
                            padding-bottom: 0.1em;
                            margin-bottom: 1em;
                            border-style: solid;
                            border-width: 1px;
                        }
                        div.Adminn ul li a{
                            color: blanchedalmond;
                        }
                        div.dropdown-menu a{
                            color: blanchedalmond;
                        }
                        div.dropdown-menu{
                            width: 5em;
                        }
                        a.dropdown-item{
                            margin-bottom: 3em;
                            background-color: black;
                        }
                    </style>
                </div>
            </div>
        </div>
    </section>
    {% else %}
    <div>
        <h1 style="font-size: 30; text-align: center;color: red;">
            <strong>ERROR DESCONOCIDO - No se encontro la propiedad con el id: {{pro.id}}</strong> 
        </h1>
    </div>
    {% endif %}


{% endblock %}

proyec_inmobiliariaPilar/apps/propiedad/templates/propiedad/eliminar_propiedad.html
{% extends "propiedad/mostrar_propiedad.html" %}

{% load static %}

{% block botones %}
<p style="color: black;">Esta seguro que desea eliminar?</p>
    <button class="btn btn-danger" style="border: 1px solid black;"><a href="{% url "eliminar_propiedad" id %}"> CONFIRMAR</a></button>
    <button class="btn btn-light" style="border: 1px solid black;"><a href="{% url "listado_propiedades" %}"> CANCELAR</a></button>
{% endblock %}

proyec_inmobiliariaPilar/apps/propiedad/templates/propiedad/lista_propiedades.html
{% extends 'base/base.html' %}

{% block contenido %}
    <style>
        div#addPropiedades{
            border: 1px solid black;
            padding: 2em;
            text-align: center;
            margin-bottom: 2em;
        }
        div#addPropiedades a{
            padding: 1em;
            color: #ffffff;
            margin: 1em;
            background-color: darkblue;
        }
        table a{
            margin-right: 1em;
            background-color: black;
        }
    </style>

    <h1 style="text-align: center;">LISTADO DE PROPIEDADES</h1>

    {% if perms.propiedad.add_propiedad %}
    <div id="addPropiedades">
        <a href="{% url 'nueva_casa' %}">NUEVA CASA</a>
        <a href="{% url 'nuevo_dpto' %}">NUEVO DEPARTAMENTO</a>
        <a href="{% url 'nueva_habitacion' %}">NUEVA HABITACION</a>
    </div>
    {% endif %}

    <div class="container">

        <div class="row">

            <div class="col-sm-2" style="border: 1px solid black;">

                <form action="" method="POST">
                    {% csrf_token %}

                    {{form}}

                    <input type="submit" value="Buscar">

                </form>

            </div>

            
            <!-- COMIENZA LA TABLA -->
            
            <div class="col-sm-10">


                <table class="table-bordered" style="width: 100%;">
                    <thead class="thead-dark" style="background-color: black;">
                    <tr style="color: blanchedalmond; text-align: center;">
                        <th scope="col">ID</th>
                        <th scope="col">TIPO</th>
                        <th scope="col">ESTADO</th>
                        <th scope="col">ZONA</th>
                        <th scope="col">FECHA INGRESO</th>
                        <th scope="col">OPCIONES</th>
                    </tr>
                    </thead>
                    {% for prop in propiedades %}
                    <tbody>
                    <tr>
                        <th scope="row">{{prop.id}}</th>
                        <td>{{prop.tipo_propiedad}}</td>
                        <td>{{prop.estado_actual}}</td>
                        <td>{{prop.zona}}</td>
                        <td>{{prop.fecha_alta}}</td>
                        <td>
                            {% if perms.propiedad.change_propiedad %}
                            <a href="{% url 'modificar_propiedad' prop.id %}">Modificar</a> 
                            {% endif %}

                            {% if perms.propiedad.delete_propiedad %}
                            <a href="{% url 'confirmar_propiedad' prop.id %}">Eliminar</a>
                            {% endif %}

                            <a href="{% url 'mostrar_propiedad' prop.id %}">Detalles</a>
                            
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>

            </div>

        </div>

    </div>

    {{mensaje}}

    
    

{% endblock %}

proyec_inmobiliariaPilar/apps/propiedad/templates/propiedad/mostrar_propiedad.html
{% extends "base/base.html" %}

{% load static %}

{% block contenido %}

<style>

    div.col-sm-5 p{
        color: black;
    }

    div.col-sm-7 p{
        padding-left: 1em;
        /* border: 1px solid black; */
        color: red;
        /* width: 85%; */
    }

</style>


<div class="container" style="text-align: center; margin-bottom: 1em;">

    <div class="row">
        <div class="col-sm-5" style="text-align: right;">
            <p>ID:</p>  
            <p>Metros:</p>  
            <p>Metros-semicubiertos:</p>  
            <p>Zona:</p>          
        </div>
        <div class="col-sm-7" style="text-align: left;">
            <strong>
            <p>{{id}}</p>            
            <p>{{mts}}</p>
            <p>{{mts_semicubiertos}}</p>
            <p>{{patio}}</p>
            </strong>
        </div>
    </div>
    <br>
    <br>
    {% block botones %}
    
    <button><a href="{% url "listado_propiedades" %}">VOLVER</a></button>

    {% endblock %}
</div>





{% endblock %}