proyec_inmobiliariaPilar/apps/contrato/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from apps.contrato import views

urlpatterns=[
    path('nuevo_contratoPropietario/', views.NuevoContrato, name='nuevo_contrato_propietario'),
    path('nuevo_contratoInquilino/', views.NuevoContrato, name='nuevo_contrato_inquilino'),
    path('listado_contratos/', views.ListadoContrato, name='listado_contratos'),
    path('modificar_contrato/<id>/', views.ModificarContrato, name='modificar_contrato'),
    path('mostrar_contrato/<id>/', views.MostrarContrato, name='mostrar_contrato'),
    path('confirmar_contrato/<id>/', views.ConfirmarEliminarContrato, name='confirmar_contrato'),
    path('eliminar_contrato/<id>/', views.EliminarContrato, name='eliminar_contrato'),
    path('confirmar_cancelacion/<id>/', views.ConfirmarCancelacion, name='confirmar_cancelacion'),
    path('cancelar_contrato/<id>/', views.CancelarContrato, name='cancelar_contrato'),
]

proyec_inmobiliariaPilar/pilar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('apps.inicio.urls'))),
    path('clientes/', include(('apps.persona.urls'))),
    path('propiedad/', include(('apps.propiedad.urls'))),
    path('busqueda/', include(('apps.busqueda.urls'))),
    path('contrato/', include(('apps.contrato.urls'))),
    path('contacto/', include(('apps.contacto.urls'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('estadisticas/', include(('apps.estadisticas.urls'))),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyec_inmobiliariaPilar/apps/contrato/models.py
from django.db import models
from apps.propiedad.models import Propiedad, Persona

# Create your models here.

class PropietarioPropiedad(models.Model):
    estados=(
        ('5','5%'),
        ('10','10%'),
        ('15','15%'),
        ('20','20%'),
        ('25','25%'),
        ('30','30%'),
    )

    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE, unique=True)
    propietario=models.ForeignKey(Persona,on_delete=models.CASCADE)
    condiciones = models.TextField()
    comision = models.CharField(max_length=5 ,choices=estados)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    fecha_alta=models.DateTimeField(auto_now_add=True)
    cancelacion = models.BooleanField(default=False)
    fecha_cancelacion = models.DateField(blank=True, null=True)

class InquilinoPropiedad(models.Model):
    propiedad=models.OneToOneField(Propiedad,on_delete=models.CASCADE)
    inquilino=models.ForeignKey(Persona,on_delete=models.CASCADE)
    fecha_alta=models.DateTimeField(auto_now_add=True)
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()
    cant_personas=models.IntegerField()
    importe_total=models.DecimalField(max_digits=10,decimal_places=2)
    cancelacion = models.BooleanField(default=False)
    fecha_cancelacion = models.DateField(blank=True, null=True)

proyec_inmobiliariaPilar/apps/contrato/forms.py
from django import forms
from django.forms import ModelForm
from .models import PropietarioPropiedad, InquilinoPropiedad
from apps.persona.models import Persona
from apps.propiedad.models import Propiedad
import datetime

class PropietarioPropiedadForm(forms.ModelForm):
    class Meta:
        model = PropietarioPropiedad
        exclude = ['cancelacion', 'fecha_cancelacion']
        widgets={
            "propiedad": forms.Select(attrs={"class":"form-control", "placeholder":"Seleccione una propiedad"}),
            "propietario": forms.Select(attrs={"class":"form-control"}),
            "fecha_inicio": forms.NumberInput(attrs={"type":"date", "class":"form-control"}),
            "fecha_fin": forms.NumberInput(attrs={"type":"date", "class":"form-control"}),
            "comision": forms.Select(attrs={"class":"form-control", "placeholder":"Importe total"}),
        }


class InquilinoPropiedadForm(forms.ModelForm):
    class Meta:
        model = InquilinoPropiedad
        exclude = ['cancelacion', 'fecha_cancelacion']
        widgets={
            "propiedad": forms.Select(attrs={"class":"form-control", "placeholder":"Seleccione una propiedad"}),
            "inquilino": forms.Select(attrs={"class":"form-control"}),
            "fecha_inicio": forms.NumberInput(attrs={"type":"date", "class":"form-control"}),
            "fecha_fin": forms.NumberInput(attrs={"type":"date", "class":"form-control"}),
            "cant_personas": forms.NumberInput(attrs={"class":"form-control", "placeholder":"Cantidad de personas que habitaran la propiedad"}),
            "importe_total": forms.NumberInput(attrs={"class":"form-control", "placeholder":"Importe total"}),
            "importe_senia": forms.NumberInput(attrs={"class":"form-control", "placeholder":"Fecha en la que FINALIZA el contrato"}),
        }

    def clean_fecha_inicio(self):
        fecha_inicio = self.cleaned_data['fecha_inicio']

        if fecha_inicio < datetime.date.today():
            raise forms.ValidationError("No puede ingresar una fecha menor que la actual")

        return fecha_inicio

    def clean_fecha_fin(self):
        fecha_fin = self.cleaned_data['fecha_fin']

        if fecha_fin < datetime.date.today():
            raise forms.ValidationError("No puede ingresar una fecha menor que la actual")

        return fecha_fin

proyec_inmobiliariaPilar/apps/contrato/views.py
from django.shortcuts import render, redirect
import datetime
from .forms import PropietarioPropiedadForm, InquilinoPropiedadForm
from apps.propiedad.models import Propiedad, Estado, Oferta
from .models import PropietarioPropiedad,InquilinoPropiedad
from apps.propiedad.views import GenerarEstado
from django.contrib import messages
from django.contrib.auth.decorators import permission_required, login_required
from pilar.settings import LOGIN_REDIRECT_URL

# Create your views here.


@login_required
def NuevoContrato(request):
    if request.user.has_perms('contrato.can_add_inquilinopropiedad', 'contrato.can_add_propietariopropiedad'):
        if request.path == '/contrato/nuevo_contratoPropietario/':
            data = {
                "form" : PropietarioPropiedadForm()
            }
            if request.method == 'POST':
                formulario = PropietarioPropiedadForm(request.POST)
                if formulario.is_valid():
                    f = formulario.save(commit=False)
                    f.cancelacion = False
                    f.fecha_cancelacion = None
                    f.save()
                    contrato = PropietarioPropiedad.objects.last()
                    data = {
                        "contrato":contrato
                    }
                    messages.success(request,'El contrato se generó correctamente')
                    return render(request, "contrato/mostrar_contrato.html", data)
                data["form"] = formulario
            
            return render(request, "contrato/nuevo_contrato.html", data)

        elif request.path == '/contrato/nuevo_contratoInquilino/':
            data = {
                "form" : InquilinoPropiedadForm()
            }
            if request.method == 'POST':
                formulario = InquilinoPropiedadForm(request.POST)
                if formulario.is_valid():
                    f = formulario.save(commit=False)
                    if f.propiedad.estado_actual == 'OCUPADO':
                        messages.error(request, 'La propiedad '+str(f.propiedad.id)+' se encuentra actualmente OCUPADA, actualice los datos de la propiedad')
                        return redirect(to='listado_propiedades')
                    if f.propiedad.estado_actual == 'EN MANTENIMIENTO':
                        messages.error(request, 'La propiedad '+str(f.propiedad.id)+' se encuentra actualmente EN MANTENIMIENTO, actualice los datos de la propiedad')
                        return redirect(to='listado_propiedades')
                    f.cancelacion = False
                    f.fecha_cancelacion = None
                    propiedad = Propiedad.objects.get(pk=f.propiedad.id)
                    if Oferta.objects.filter(propiedad = propiedad).exists():
                        oferta = Oferta.objects.get(propiedad = propiedad)
                        oferta.delete()
                    propiedad.estado_actual = 'OCUPADO'
                    propiedad.save()
                    GenerarEstado(propiedad)
                    f.save()
                    contrato = InquilinoPropiedad.objects.last()
                    data = {
                        "contrato":contrato
                    }
                    messages.success(request,'El contrato se generó correctamente')
                    return render(request, "contrato/mostrar_contrato.html", data)
                data["form"] = formulario

        return render(request, "contrato/nuevo_contrato.html", data)
    
    else:
        messages.error(request,'No cuenta con permiso para agregar contratos')
        return redirect(to='index')


@login_required
def ModificarContrato(request, id):
    if request.user.has_perms('contrato.can_change_inquilinopropiedad', 'contrato.can_change_propietariopropiedad'): 
        if PropietarioPropiedad.objects.filter(pk = id).exists():
            contrato = PropietarioPropiedad.objects.get(pk = id)
            if contrato.cancelacion:
                messages.error(request, 'No se puede modificar un contrato cancelado')
                return redirect(to='listado_contratos')
            data = {
                "form":PropietarioPropiedadForm(instance=contrato)
            }
            if request.method == 'POST':
                formulario = PropietarioPropiedadForm(data=request.POST, instance=contrato)
                if formulario.is_valid():
                    formulario.save()
                    data={
                    "mensaje":'guardado correctamente',
                    "form": PropietarioPropiedadForm(instance=contrato),
                    }
                data["form"] = formulario        

        elif InquilinoPropiedad.objects.filter(pk = id).exists():
            contrato = InquilinoPropiedad.objects.get(pk= id)
            if contrato.cancelacion:
                messages.error(request, 'No se puede modificar un contrato cancelado')
                return redirect(to='listado_contratos')
            prop_ant = Propiedad.objects.get(pk = contrato.propiedad.id)
            data = {
                "form":InquilinoPropiedadForm(instance=contrato)
            }
            if request.method == 'POST':
                formulario = InquilinoPropiedadForm(data=request.POST, instance=contrato)
                if formulario.is_valid():
                    f = formulario.save(commit=False)
                    prop_nueva = f.propiedad
                    if prop_ant != prop_nueva:
                        prop_ant.estado_actual = 'DISPONIBLE'
                        prop_ant.save()
                        GenerarEstado(prop_ant)
                        prop_nueva.estado_actual = 'OCUPADO'
                        prop_nueva.save()
                        GenerarEstado(prop_nueva)
                    f.save()
                    data={
                    "mensaje":'guardado correctamente',
                    "form": InquilinoPropiedadForm(instance=contrato),
                    }
                data["form"] = formulario
        return render(request, "contrato/nuevo_contrato.html", data)     
    else:
        messages.error(request,'No cuenta con permiso para modificar contratos')
        return redirect(to='index')


@login_required
def MostrarContrato(request, id):
    if request.user.has_perms('contrato.can_view_inquilinopropiedad', 'contrato.can_view_propietariopropiedad'):
        data={
            "queti":'qwqweeqwes'
        }
        if InquilinoPropiedad.objects.filter(pk=id).exists():
            contrato = InquilinoPropiedad.objects.get(pk=id)
            data = {
                "contrato":contrato
            }
        return render(request, 'contrato/mostrar_contrato.html', data)
    else:
        messages.error(request,'No cuenta con permiso para visualizar los contratos')
        return redirect(to="index")


@login_required
def ConfirmarEliminarContrato(request, id):
    if request.user.has_perms('contrato.can_delete_inquilinopropiedad', 'contrato.can_delete_propietariopropiedad'):
        data={
            "queti":'qwqweeqwes'
        }
        if InquilinoPropiedad.objects.filter(pk=id).exists():
            contrato = InquilinoPropiedad.objects.get(pk=id)
            data = {
                "contrato":contrato
            }
        if PropietarioPropiedad.objects.filter(pk=id).exists():
            contrato = PropietarioPropiedad.objects.get(pk=id)
            data = {
                "contrato":contrato
            }
        return render(request, 'contrato/eliminar_contrato.html', data)
    else:
        messages.error(request,'No tienes permisos para eliminar contratos')
        return redirect(to = "index")


@login_required
def EliminarContrato(request, id):
    if request.user.has_perms('contrato.can_delete_inquilinopropiedad','contrato.can_delete_propietariopropiedad'):
        if PropietarioPropiedad.objects.filter(pk = id).exists():
            contrato = PropietarioPropiedad.objects.get(pk = id)
            if contrato.cancelacion:
                messages.error(request,'No se puede eliminar un contrato cancelado')
                return redirect(to='listado_contratos')
            contrato.delete()
            messages.success(request,'SE HA ELIMINADO CON EXITO')
        elif InquilinoPropiedad.objects.filter(pk = id).exists():
            contrato = InquilinoPropiedad.objects.get(pk= id)
            if contrato.cancelacion:
                messages.error(request,'No se puede eliminar un contrato cancelado')
                return redirect(to='listado_contratos')
            propiedad = Propiedad.objects.get(pk=contrato.propiedad.id)
            propiedad.estado_actual = 'DISPONIBLE'
            propiedad.save()
            GenerarEstado(propiedad)
            contrato.delete()
            messages.success(request,'SE HA ELIMINADO CON EXITO')     

        return redirect(to='listado_contratos')
    else:
        messages.error(request,'No tienen permiso para eliminar contratos')
        return redirect(to="index")


@login_required
def ListadoContrato(request):
    if request.user.has_perms('contrato.can_view_inquilinopropiedad', 'contrato.can_view_propietariopropiedad'):
        contratosPropietarios = PropietarioPropiedad.objects.all()
        contratosInquilinos = InquilinoPropiedad.objects.all() 
        data = {
            "propietarios" : contratosPropietarios,
            "inquilinos": contratosInquilinos
        }
        return render(request,"contrato/listado_contratos.html", data)
    else:
        messages.error(request,'No cuentas con permisos para visualizar los contratos')
        return redirect(to = "index")

@login_required
def ConfirmarCancelacion(request,id):
    if request.user.has_perms('contrato.can_change_inquilinopropiedad', 'contrato.can_change_propietariopropiedad'):
        data={
            "queti":'qwqweeqwes'
        }
        if InquilinoPropiedad.objects.filter(pk=id).exists():
            contrato = InquilinoPropiedad.objects.get(pk=id)
            if contrato.cancelacion:

proyec_inmobiliariaPilar/apps/contrato/templates/contrato/cancelar_contrato.html
{% extends "contrato/mostrar_contrato.html" %}

{% load static %}


{% block titulo %}
<h3>¿ESTAS SEGURO DE CANCELAR EL CONTRATO NUMERO: {{contrato.id}}?</h3>
<p>Al cancelar el contrato la propiedad quedará disponible para otro contrato, el contrato quedara en el sistema se aplicara una fecha de cancelacion, pero no se podrá modificar </p>
{% endblock %}



{% block botones %}
<p style="color: black;">Esta seguro que desea cancelar el contrato?</p>
<button class="btn btn-danger" style="border: 1px solid black;"><a href="{% url "cancelar_contrato" contrato.id %}"> CONFIRMAR</a></button>
<button class="btn btn-light" style="border: 1px solid black;"><a href="{% url "listado_contratos" %}">CANCELAR</a></button>
{% endblock %}

proyec_inmobiliariaPilar/apps/contrato/templates/contrato/eliminar_contrato.html
{% extends "contrato/mostrar_contrato.html" %}

{% load static %}


{% block titulo %}
<h3>¿QUIERES ELIMINAR EL CONTRATO NUMERO: {{contrato.pk}}?</h3>
{% endblock %}



{% block botones %}
<p style="color: black;">Esta seguro que desea eliminar?</p>
<button class="btn btn-danger" style="border: 1px solid black;"><a href="{% url "eliminar_contrato" contrato.pk %}"> CONFIRMAR</a></button>
<button class="btn btn-light" style="border: 1px solid black;"><a href="{% url "listado_contratos" %}">CANCELAR</a></button>
{% endblock %}

proyec_inmobiliariaPilar/apps/contrato/templates/contrato/listado_contratos.html
{% extends "base/base.html" %}

{% load static %}

{% block contenido %}

<style>

    div#addPropiedades{
        text-align: center;
        margin-bottom: 2em;
    }

    div#addPropiedades button{
        margin-top: 2px;
        width: 20em;
    }

    div#addPropiedades button a{
        color: #ffffff;
    }

</style>

<div class="container">

<h1 style="text-align: center;">LISTADO DE CONTRATOS</h1>

<div id="addPropiedades">
    {% if perms.contrato.add_propietariopropiedad %}
        <button class="btn btn-primary btn-lg"><a href="{% url 'nuevo_contrato_propietario' %}">NUEVO CONTRATO PROPIETARIO</a></button>
    {% endif %}

    {% if perms.contrato.add_inquilinopropiedad %}
        <button class="btn btn-primary btn-lg"><a href="{% url 'nuevo_contrato_inquilino' %}">NUEVO CONTRATO INQUILINO</a></button>
    {% endif %}
</div>

<table class="table-bordered" style="width: 100%;">
    <thead class="thead-dark" style="background-color: black;">
    <tr style="color: blanchedalmond; text-align: center;">
        <th scope="col">ID</th>
        <th scope="col">CLIENTE</th>
        <th scope="col">TIPO CONTRATO</th>
        <th scope="col">FECHA ALTA</th>
        <th scope="col">FECHA FIN</th>
        <th scope="col">OPCIONES</th>
    </tr>
    </thead>
    <tbody>
    {% for contrato in propietarios %}
    <tr>
        <th scope="row">{{contrato.id}}</th>
        <td>{{contrato.propietario.personafisica.nombre}},{{contrato.propietario.personafisica.apellido}}{{contrato.propietario.personajuridica.razon_social}}</td>
        <td>CONTRATO PROPIEDAD</td>
        <td>{{contrato.fecha_alta}}</td>
        <td>{{contrato.fecha_inicio}}</td>
        <td>
            {% if perms.contrato.change_propietariopropiedad %}
            <button><a href="{% url 'modificar_contrato' contrato.id %}">Modificar</a></button>
            {% endif %}

            {% if perms.contrato.delete_propietariopropiedad %}
            <button><a href="{% url 'confirmar_contrato' contrato.id %}">Eliminar</a></button>
            {% endif %}

            <button><a href="{% url 'mostrar_contrato' contrato.id %}">Detalles</a></button>

        </td>
    </tr>
    {% endfor %}
    {% for contrato in inquilinos %}
    <tr>
        <th scope="row">{{contrato.id}}</th>
        <td>{{contrato.inquilino.personafisica.nombre}},{{contrato.inquilino.personafisica.apellido}}{{contrato.inquilino.personajuridica.razon_social}}</td>
        <td>CONTRATO ALQUILER</td>
        <td>{{contrato.fecha_alta}}</td>
        <td>{{contrato.fecha_inicio}}</td>
        <td>
            {% if perms.contrato.change_inquilinopropiedad %}
            <button><a href="{% url 'modificar_contrato' contrato.id %}">Modificar</a></button>
            {% endif %}

            {% if perms.contrato.delete_inquilinopropiedad %}
            <button><a href="{% url 'confirmar_contrato' contrato.id %}">Eliminar</a></button>
            {% endif %}

            <button><a href="{% url 'mostrar_contrato' contrato.id %}">Detalles</a></button>
            <button><a href="{% url 'confirmar_cancelacion' contrato.id %}">Cancelar</a></button>

        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

</div>

{% endblock %}

proyec_inmobiliariaPilar/apps/contrato/templates/contrato/mostrar_contrato.html
{% extends "base/base.html" %}

{% load static %}

{% block contenido %}

<style>

    div.col-sm-5 p{
        color: black;
    }

    div.col-sm-7 p{
        padding-left: 1em;
        /* border: 1px solid black; */
        color: red;
        /* width: 85%; */
    }

</style>


<div class="container" style="text-align: center; margin-bottom: 1em;">

    {% block titulo %}

    {% endblock %}

    {% if contrato.comision %}
    <div class="row">
        <div class="col-sm-5" style="text-align: right;">
            <p>ID:</p>                                  
            <p>Cliente:</p>
            <p>Tipo de Cliente:</p>  
            <p>Direccion:</p>  
            <p>Propiedad:</p>
            <p>Comision:</p>
            <p>Importe:</p>
            <p>fecha_inicio:</p>
            <p>fecha_fin:</p>          
        </div>
        <div class="col-sm-7" style="text-align: left;">
            <strong>
            <p>{{contrato.pk}}</p>
            <p>{{contrato.propietario}}</p>            
            <p>{{contrato.propietario.desc_per}}</p>
            <p>{{contrato.propietario.provincia}},{{contrato.propietario.localidad}},{{contrato.propietario.barrio}},{{contrato.propietario.calle}},{{contrato.propietario.numero}}</p>
            <p>{{contrato.propiedad}}</p>
            <p>{{contrato.comision}}</p>
            <p>{{contrato.propiedad.precio}}</p>
            <p>{{contrato.fecha_inicio}}</p>
            <p>{{contrato.fecha_fin}} </p>
            </strong>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-sm-5" style="text-align: right;">
            <p>ID:</p>                                  
            <p>Cliente:</p>
            <p>Tipo de Cliente:</p>  
            <p>Direccion:</p>  
            <p>Propiedad:</p>
            <p>Cantidad de personas:</p>
            <p>Importe Total:</p>
            <p>fecha_inicio:</p>
            <p>fecha_fin:</p>          
        </div>
        <div class="col-sm-7" style="text-align: left;">
            <strong>
            <p>{{contrato.pk}}</p>
            <p>{{contrato.inquilino}}</p>            
            <p>{{contrato.inquilino.desc_per}}</p>
            <p>{{contrato.inquilino.provincia}},{{contrato.inquilino.localidad}},{{contrato.inquilino.barrio}},{{contrato.inquilino.calle}},{{contrato.inquilino.numero}}</p>
            <p>{{contrato.propiedad}}</p>
            <p>{{contrato.cant_personas}}</p>
            <p>{{contrato.importe_total}}</p>
            <p>{{contrato.fecha_inicio}}</p>
            <p>{{contrato.fecha_fin}} </p>
            </strong>
        </div>
    </div>



    {% endif %}
    <br>
    <br>

    {% block botones %}
    <button class="btn btn-primary" style="border: 1px solid black;"><a style="color: white;" href="{% url "listado_contratos" %}">VOLVER</a></button>
    {% endblock %}
</div>



{% endblock %}

proyec_inmobiliariaPilar/apps/contrato/templates/contrato/nuevo_contrato.html
{% extends 'base/base.html' %}

{% load static %}

{% block contenido %}

<style>
    div.container{

        margin-bottom: 1em;
        margin-top: 1em;

    }

    div.form-group.row{

        margin-top: 1em;
        margin-left: 1em;
        margin-right: 1em;
        vertical-align: middle;

    }

    div.input-field select{
        
        display: block;
        margin: 0;
        width: 100%;
    }

</style>

    <div class="container" style="background-image: url({% static 'base/fondo-formulariopersona.jpg' %});">
        <form action="" method="POST">{% csrf_token %}
    {% for field in form %} 
        <div class="form-group row">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label" style="color: #fff;">{{field.label}}</label>
            <div class="col-sm-10">
                {{field}}
                {{field.errors}}
            </div>
        </div>
    {% endfor %}
        <div class="input-field" style="padding: 3em; text-align: center;" >
            <input class="btn-primary" type="submit" name="ENVIAR">
            <input class="btn-primary" type="reset" name="RESET">
        </div>
            <h3>{{mensaje}}</h3>
        </form>
    </div>

{% endblock %}